import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import {dark} from "@clerk/themes";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Website Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
   <ClerkProvider
      appearance={{
        baseTheme: dark,
        elements: {
          card: "bg-gray-900 border border-gray-700 shadow-sm",
          headerTitle: "text-white",
          formFieldInput: "bg-gray-800 border border-gray-700 text-white",
          formFieldLabel: "text-gray-300",
          formButtonPrimary:
            "bg-blue-600 hover:bg-blue-700 text-white font-medium",
          footerActionText: "text-gray-400 hover:text-gray-200",
        },
      }}
    >
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
} 